FROM arm64v8/node:alpine
MAINTAINER Said Sef <saidsef@gmail.com>

LABEL "uk.co.saidsef.aws-kinesis"="Said Sef Associates Ltd"
LABEL version="2.0"

ARG PORT=""

ENV NODE_ENV production
ENV PORT ${PORT:-4567}

RUN npm install kinesalite

EXPOSE ${PORT}

WORKDIR /app

CMD ["/app/node_modules/.bin/kinesalite"]
ENTRYPOINT ["/app/node_modules/.bin/kinesalite"]
