FROM arm64v8/python:3-alpine
MAINTAINER Said Sef <saidsef@gmail.com>

LABEL "uk.co.saidsef.aws-kinesis"="Said Sef Associates Ltd"
LABEL version="2.0"

ARG PORT=""

ENV NODE_ENV production
ENV PORT ${PORT:-4567}

RUN apk add -U nodejs npm
RUN npm install kinesalite

EXPOSE ${PORT}

WORKDIR /app

CMD ["/node_modules/.bin/kinesalite"]
ENTRYPOINT ["/node_modules/.bin/kinesalite"]
