---
apiVersion: v1
kind: Service
metadata:
  name: kinesis
  labels:
    app.kubernetes.io/name: kinesis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kinesis
  ports:
    - port: 80
      protocol: TCP
      targetPort: tcp
      name: tcp
