---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kinesis
  labels:
    app.kubernetes.io/name: kinesis
spec:
  serviceName: "kinesis"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kinesis
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4567"
      labels:
        app.kubernetes.io/name: kinesis
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      terminationGracePeriodSeconds: 60
      containers:
        - image: docker.io/saidsef/aws-kinesis-local:v2023.01
          name: kinesis
          imagePullPolicy: Always
          tty: true
          ports:
            - protocol: TCP
              containerPort: 4567
              name: tcp
          resources:
            limits:
              memory: 1Gi
              cpu: 200m
            requests:
              memory: 512Mi
              cpu: 100m
          livenessProbe:
            exec:
              command:
                - pgrep
                - node
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
                port: tcp
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            runAsNonRoot: true
            runAsGroup: 65534
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
             drop:
               - ALL
          volumeMounts:
            - name: storage
              mountPath: /data
              subPath: data
              readOnly: false
      volumes:
        - name: storage
          emptyDir:
            sizeLimit: 1Gi
