apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamedb
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/saidsef/aws-dynamodb-local.git
    targetRevision: HEAD
    path: deployment

    # directory
    directory:
      recurse: true

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: web

  # Sync policy
  syncPolicy:
    automated:
      prune: true
