apiVersion: v1
kind: Service
metadata:
  name: {{ include "kinesis.fullname" . }}
  labels:
    {{- include "kinesis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.healess }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "kinesis.selectorLabels" . | nindent 4 }}
